services:
  app:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    entrypoint: ["sh", "./docker-entrypoint.sh"]
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:9292", "config.ru"]